### ISSUE TITLE
DB migration issue

### ISSUE THREAD

**Issue by MoonSeongKwang** [gruut/gruut#82]
https://github.com/gruut/gruut/wiki/DB-migration

현재 위와 같은 방법으로 실행하여 데이터베이스를 구축할 경우,
```
Mysql2::Error: Specified key was too long; max key length is 767 bytes: CREATE TABLE `contract_scope` (`csidx` int NOT NULL AUTO_INCREMENT PRIMARY KEY, `contract_id` varchar(255), `var_name` varchar(255), `var_value` text, `var_type` tinyint, `var_info` text, `up_time` bigint, `pid` char(44), UNIQUE INDEX `index_contract_scope_on_contract_id`  (`contract_id`), UNIQUE INDEX `index_contract_scope_on_pid`  (`pid`))
```
라는 에러와 함께 테이블 생성에 실패합니다.

찾아보니, https://stackoverflow.com/a/1814594 의 이슈와 관련되어 있습니다.
wiki 페이지에서 써있는 `encoding: utf8mb4`는 글자 당 4바이트의 할당이 되어있어서 varchar(255)가 767바이트의 제한을 넘깁니다.
답변에 따르면 MySQL의 버전을 올리거나,  encoding을 글자 당 3바이트인 utf8로 지정하면 해결된다고 합니다.
실제로 uft8로 encoding을 변경하는 방법으로는 테이블이 정상적으로 생성되는 것을 확인하였습니다.

해결 방법에 대해 의견 부탁드립니다.

**Comment by morishjs** [comment]
@SeongKwangMoon 

MySQL의 기본 인코딩이 `utf8mb4`로 바뀐 것이 굉장히 오래 전으로 알고 있습니다. 제 생각엔 MySQL의 버전을 올리는게 best 인 것 같습니다.

**Comment by MoonSeongKwang** [comment]
@park53kr 

MariaDB 기준 10.1 버전에서는 지원이 되지 않았는데, 10.3으로 버전을 올린 다음에는 정상적으로 구동됩니다. 문제가 해결되었습니다.
10.2나 10.3에서부터 key의 길이가 늘어나서 지원 가능해지는 버전이라고 합니다.
wiki 페이지에 설명을 덧붙여주시거나 하시면 좋을 것 같습니다.

**Comment by MoonSeongKwang** [comment]
아, 그리고 테이블의 구조는 NOT NULL 등의 세부적인 옵션 설정에서 조금 더 변경이 있을 것 같습니다.
